project:
  type: website

website:
  title: "quartotheme"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
